[package]
name = "y-sync"
version = "0.1.0"
edition = "2021"
description = "Yrs synchronization protocol"
license = "MIT"
authors = ["Bartosz Sypytkowski <b.sypytkowski@gmail.com>"]
keywords = ["crdt", "yrs", "y-sync"]
homepage = "https://github.com/y-crdt/y-sync/"
repository = "https://github.com/y-crdt/y-sync/"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib0 = { path = "../y-crdt/lib0" }
yrs = { path = "../y-crdt/yrs" }
thiserror = "1.0"

[dev-dependencies]
