[package]
name = "y-sync"
version = "0.3.0"
edition = "2021"
description = "Yrs synchronization protocol"
license-file = "LICENSE"
authors = ["Bartosz Sypytkowski <b.sypytkowski@gmail.com>"]
keywords = ["crdt", "yrs", "y-sync"]
homepage = "https://github.com/y-crdt/y-sync/"
repository = "https://github.com/y-crdt/y-sync/"
readme = "./README.md"

[features]
net = ["dep:tokio", "dep:futures-util"]

[dependencies]
lib0 = ">= 0.16"
yrs = ">= 0.16"
thiserror = "1.0"
tokio = { version = "1.26.0", features = ["net", "sync"], optional = true }
futures-util = { version = "0.3", features = ["sink"], optional = true }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["full"] }
tokio-util = { version ="0.7", features = ["codec"] }
bytes = "1.4"

[patch.crates-io]
lib0 = { git = "https://github.com/toeverything/y-crdt", rev = "9dfe53c" }
yrs = { git = "https://github.com/toeverything/y-crdt", rev = "9dfe53c" }